spring-webflux:
  database:
    host: localhost
    port: 5435
    name: webfluxdb
    schema: public
    username: userdb
    password: pwduserdb
    pool:
    size:
      initial: 3
      max: 10

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5435/webfluxdb
    username: userdb
    password: pwduserdb

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5435/webfluxdb
    user: userdb
    password: pwduserdb
    baseline-version: 0


server:
  port: 8081